version: '2'
services:
  mysql:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'
    volumes:
      - ./mysql_data:/var/lib/mysql
 
  fpm:
    build: ./fpm
    restart: always
    links:
      - mysql
    volumes:
      - moodle_web:/moodle/web
      - ./fpm/www-pool.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./conf.d/:/moodle/conf.d/
      - ./moodle_data:/moodle/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
    environment:
      - DB_HOST=mysql
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
    volumes:
      - moodle_web:/moodle/web
      - ./conf.d/:/moodle/conf.d/
      - ./moodle_data:/moodle/data

volumes:
  moodle_web:
