version: '2'
services:
  mysql:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
    volumes:
      - ./mysql_data:/var/lib/mysql
 
  fpm:
    build: ./fpm
    restart: always
    links:
      - mysql
    environment:
      - MOODLE_DOMAIN=machine.dev
      - SMTP_SERVER=smtp.litnet.lt
    volumes:
      - moodle_web:/moodle/web
      - ./conf.d/:/moodle/conf.d/
      - ./moodle_data:/moodle/data

  web:
    build: ./web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm
    environment:
      - DB_HOST=mysql
      - DB_NAME=moodle
      - DB_USER=moodle
      - DB_PASS=moodle
    volumes:
      - moodle_web:/moodle/web
      - ./certs:/etc/ssl/nginx
      - ./conf.d:/moodle/conf.d
      - ./moodle_data:/moodle/data

volumes:
  moodle_web:
